In [1]:
import pandas as pd

In [2]:
country_data = pd.read_csv('~/Documents/Monitoring-Global-Development-Aid-With-Machine-Learning/Data/activity_cluster_data.csv')

country_data

,Year,RecipientName,cluster,USD_Disbursement,country_code,IncomegroupName,Sector
0,2000,Afghanistan,2,0.000000,AFG,LDCs,Health
1,2000,Afghanistan,5,5.944185,AFG,LDCs,Refugees in Donor Countries
2,2000,Afghanistan,11,0.683999,AFG,LDCs,"Conflict, Peace & Security"
3,2000,Afghanistan,12,0.708639,AFG,LDCs,Government & Civil Society
4,2000,Afghanistan,13,0.086285,AFG,LDCs,Other Multisector
...,...,...,...,...,...,...,...
297642,2019,Zimbabwe,211,4.147414,ZWE,Other LICs,Health
297643,2019,Zimbabwe,214,1.120344,ZWE,Other LICs,Energy
297644,2019,Zimbabwe,221,0.050000,ZWE,Other LICs,Energy
297645,2019,Zimbabwe,225,23.510779,ZWE,Other LICs,Health
297646,2019,Zimbabwe,226,0.000000,ZWE,Other LICs,Health

In [3]:
country_data.RecipientName.unique()

array(['Afghanistan', 'Africa, regional', 'Albania', 'Algeria',
       'America, regional', 'Angola', 'Anguilla', 'Antigua and Barbuda',
       'Argentina', 'Armenia', 'Asia, regional', 'Azerbaijan', 'Bahrain',
       'Bangladesh', 'Barbados', 'Belize', 'Benin', 'Bhutan',
       'Bilateral, unspecified', 'Bolivia', 'Bosnia and Herzegovina',
       'Botswana', 'Brazil', 'Burkina Faso', 'Burundi', 'Cabo Verde',
       'Cambodia', 'Cameroon', 'Central African Republic',
       'Central Asia, regional', 'Chad', 'Chile',
       "China (People's Republic of)", 'Colombia', 'Comoros', 'Congo',
       'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba', "Côte d'Ivoire",
       "Democratic People's Republic of Korea",
       'Democratic Republic of the Congo', 'Djibouti', 'Dominica',
       'Dominican Republic', 'Ecuador', 'Egypt', 'El Salvador',
       'Equatorial Guinea', 'Eritrea', 'Eswatini', 'Ethiopia',
       'Europe, regional', 'Far East Asia, regional', 'Fiji', 'Gabon',
       'Gambia', 'Georgia', 'Ghana', 'Grenada', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Honduras', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Jamaica', 'Jordan', 'Kazakhstan',
       'Kenya', 'Kiribati', 'Kyrgyzstan',
       "Lao People's Democratic Republic", 'Lebanon', 'Lesotho',
       'Liberia', 'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali',
       'Malta', 'Marshall Islands', 'Mauritania', 'Mauritius', 'Mayotte',
       'Mexico', 'Micronesia', 'Middle East, regional', 'Moldova',
       'Mongolia', 'Montenegro', 'Montserrat', 'Morocco', 'Mozambique',
       'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Nicaragua', 'Niger',
       'Nigeria', 'Niue', 'North & Central America, regional',
       'North Macedonia', 'North of Sahara, regional',
       'Oceania, regional', 'Oman', 'Pakistan', 'Palau', 'Panama',
       'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Rwanda',
       'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Slovenia', 'Solomon Islands',
       'Somalia', 'South & Central Asia, regional', 'South Africa',
       'South America, regional', 'South of Sahara, regional',
       'Sri Lanka', 'States Ex-Yugoslavia unspecified', 'Sudan',
       'Suriname', 'Syrian Arab Republic', 'Tajikistan', 'Tanzania',
       'Thailand', 'Timor-Leste', 'Togo', 'Tokelau', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'Uganda', 'Uruguay',
       'Uzbekistan', 'Vanuatu', 'Venezuela', 'Viet Nam',
       'Wallis and Futuna', 'West Bank and Gaza Strip',
       'West Indies, regional', 'Yemen', 'Zambia', 'Zimbabwe', 'Belarus',
       'Libya', 'South Asia, regional', 'Ukraine', 'Kosovo',
       'South Sudan', 'Caribbean & Central America, regional',
       'Caribbean, regional', 'Central America, regional',
       'Eastern Africa, regional', 'Melanesia, regional',
       'Middle Africa, regional', 'Polynesia, regional',
       'Southern Africa, regional', 'Western Africa, regional'],
      dtype=object)

In [4]:
sids = ['Anguilla', 'Antigua and Barbuda', 'Bahrain', 'Barbados', 'Belize', 'Cabo Verde', 'Comoros', 
             'Cook Islands', 'Dominica', 'Dominican Republic', 'Fiji', 'Grenada', 'Guinea-Bissau', 'Guyana', 
             'Haiti', 'Jamaica', 'Kiribati', 'Maldives', 'Marshall Islands', 'Mauritius', 'Micronesia', 
             'Montserrat', 'Nauru', 'Niue', 'Palau', 'Papua New Guinea', 'Saint Kitts and Nevis', 'Saint Lucia', 
             'Saint Vincent and the Grenadines', 'Samoa', 'Sao Tome and Principe', 'Seychelles', 'Solomon Islands', 
             'Suriname', 'Timor-Leste', 'Tokelau', 'Tonga', 'Trinidad and Tobago', 'Turks and Caicos Islands', 
             'Tuvalu', 'Vanuatu']

In [6]:
sids_data = country_data[country_data['RecipientName'].isin(sids)]

sids_data

,Year,RecipientName,cluster,USD_Disbursement,country_code,IncomegroupName,Sector
374,2000,Anguilla,19,0.015138,AIA,MADCTs,Energy
375,2000,Anguilla,29,0.000922,AIA,MADCTs,Tourism
376,2000,Anguilla,31,0.134726,AIA,MADCTs,Government & Civil Society
377,2000,Anguilla,38,0.000000,AIA,MADCTs,Education
378,2000,Anguilla,58,0.236149,AIA,MADCTs,Transport
...,...,...,...,...,...,...,...
296779,2019,Vanuatu,212,0.082345,VUT,LDCs,Health
296780,2019,Vanuatu,213,0.000000,VUT,LDCs,Energy
296781,2019,Vanuatu,214,0.020712,VUT,LDCs,Energy
296782,2019,Vanuatu,216,0.033270,VUT,LDCs,Energy
296783,2019,Vanuatu,227,0.209376,VUT,LDCs,Health

In [7]:
country_data.Sector.unique()

array(['Health', 'Refugees in Donor Countries',
       'Conflict, Peace & Security', 'Government & Civil Society',
       'Other Multisector', 'Emergency Response', 'Energy', 'Education',
       'Agriculture', 'Water Supply & Sanitation', 'Transport',
       'Social Infrastructure & Services',
       'Developmental Food Aid/Food Security Assistance',
       'Reconstruction Relief & Rehabilitation', 'Environment',
       'Mineral Resources & Mining', 'General Budget Support',
       'Population Policies/Programmes', 'Business & Other Services',
       'Trade Policies & Regulations', 'Industry', 'Forestry',
       'Communications', 'Fishing', 'Banking & Financial Services',
       'Action Relating to Debt', 'Tourism', 'Culture',
       'Solid Waste and Recycling',
       'Safety of nuclear power plants and safeguards',
       'Volunteer Programs & Services'], dtype=object)

In [12]:
data2 = pd.read_excel('~/Documents/Monitoring-Global-Development-Aid-With-Machine-Learning/Data/descriptive_statistics_clusters.xlsx')
data2

,Cluster,Topic,matching Purpose Code,Purpose Code,Area,Sum Disbursement,Count Activities
0,56,Relief of debt,yes,60030/60020,Action Relating to Debt,157557.714495,11865
1,6,Irrigation systems,no,NaN,Agriculture,16771.201091,23762
2,49,Agricultural development,yes,31120,Agriculture,39146.564830,79393
3,63,"Agricultural research, development and technol...",no,NaN,Agriculture,13653.854790,26581
4,99,Agricultural alternative development,yes,31165,Agriculture,3706.952524,3459
...,...,...,...,...,...,...,...
168,68,Water resource management,no,NaN,Water Supply & Sanitation,4798.888321,8909
169,72,Water supply and sanitation,yes,14020,Water Supply & Sanitation,99736.154509,109260
170,76,River basin management,no,NaN,Water Supply & Sanitation,5844.944549,7946
171,121,Water policy and governance,yes,14010,Water Supply & Sanitation,13814.859861,18571
172,208,Sanitation and wastewater treatment,no,NaN,Water Supply & Sanitation,10286.968895,10975